#include <SDL2/SDL.h>
#include <stdio.h>

#ifndef _GLOBAL_CONSTANTS
#define _GLOBAL_CONSTANTS

#if 0
#define __DEBUG_SELECT_WINDOW__
#endif

#define SCREEN_WIDTH 672
#define SCREEN_HEIGHT 568

#define SPRITE_CANVAS_SIZE 64
#define SPRITE_CANVAS_PIXEL_SIZE 50
#define SPRITE_CANVAS_ROW_SIZE 8

#define COLORPICKER_PIXEL_SIZE 50
#define COLORPICKER_CANVAS_SIZE 16
#define COLORPICKER_XOFFSET 440
#define COLORPICKER_YOFFSET 40
#define COLORPICKER_ROW_SIZE 4

#define SPRITESHEET_SIZE 64
#define SPRITESHEET_CANVAS_SIZE 64
#define SPRITESHEET_CELL_SIZE 42
#define SPRITESHEET_PIXEL_SIZE 5
#define SPRITESHEET_ROW_SIZE 16
#define SPRITESHEET_COL_SIZE 4
#define SPRITESHEET_YOFFSET 400

#endif
